# -*- coding: utf-8 -*-
"""1Work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtc7aNtXlWZhRnWv-5xBxv3oZPd3zN9L
"""


import pandas as pd
import numpy as np

data = pd.read_csv('https://gist.githubusercontent.com/jtrive84/c87434e3d7838a49fbc5263f9af96bbc/raw/834ca299a92787ccf829c3e21f5d28db94ef6a32/mw.csv')
data.head()

y=data['GENDER']
X= data.drop(['GENDER'],axis=1)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(X,y, test_size=0.1, random_state=1)

from keras.layers import Dense
from keras.models import Sequential

model = Sequential()

model.add(Dense(units=40,activation='relu',input_dim=(X_train.shape[1])))
model.add(Dense(units=40, activation='relu'))

model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=50, activation='relu'))

model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

mymodelfit = model.fit(X_train, y_train, epochs=200, batch_size=80, validation_data=(X_test,y_test))
