# -*- coding: utf-8 -*-
"""2Work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jYn9wEsO_zt_lMNW-qJEsSxN7vw8l5m
"""

import pandas as pd
import numpy as np

data = pd.read_csv('https://raw.githubusercontent.com/sanky2501/Data-Preprocessing-and-Multiple-Linear-Regression-in-Python/master/Placement_data.csv')
data.head()

data.isnull().any()

data['salary'] = data['salary'].fillna(data['salary'].mean())

data.isnull().any()

from sklearn.preprocessing import LabelEncoder

for column in data.columns:
  if data[column].dtype=='object':
    data[column]=LabelEncoder().fit_transform(data[column])

X = data.drop('salary', axis=1)
y = data['salary']

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(X,y, test_size=0.2,random_state=1)

from keras.layers import Dense
from keras.models import Sequential

model =Sequential()

model.add(Dense(units=50, activation='relu', input_dim=(X_train.shape[1])))
model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=50, activation='relu'))

model.add(Dense(units=30, activation='relu'))
model.add(Dense(units=20, activation='relu'))
model.add(Dense(units=1))

model.compile(loss='mean_squared_error', optimizer='adam')

mymodel = model.fit(X_train, y_train, epochs=100, batch_size=40, verbose=1, validation_data=(X_test, y_test))